# Generated by Django 5.1.2 on 2024-11-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
